#!/usr/bin/env python3
# -*- coding: utf-8 -*-

''' dumptrump
Ben Crisp 2019 (ben.crisp@framestore.com)

Dump a Trump quote (and optionally some ASCII art of his ugly mug)

Uses the API provided by "What does Trump think?" to obtain quotes
'''

import argparse
import requests
from requests.exceptions import HTTPError
from argparse import RawTextHelpFormatter

api_base_uri = 'https://api.whatdoestrumpthink.com/api/v1'
api_random_quote_endpoint = 'quotes/random'

trump = '''
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠋⠉⡉⣉⡛⣛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡿⠋⠁⠄⠄⠄⠄⠄⢀⣸⣿⣿⡿⠿⡯⢙⠿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡿⠄⠄⠄⠄⠄⡀⡀⠄⢀⣀⣉⣉⣉⠁⠐⣶⣶⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠁⣿⣿⣀⠈⠿⢟⡛⠛⣿⠛⠛⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡆⠄⠄⠄⠄⠄⠈⠁⠰⣄⣴⡬⢵⣴⣿⣤⣽⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⠄⢀⢄⡀⠄⠄⠄⠄⡉⠻⣿⡿⠁⠘⠛⡿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡿⠃⠄⠄⠈⠻⠄⠄⠄⠄⢘⣧⣀⠾⠿⠶⠦⢳⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣶⣤⡀⢀⡀⠄⠄⠄⠄⠄⠄⠻⢣⣶⡒⠶⢤⢾⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠟⠋⠄⢘⣿⣦⡀⠄⠄⠄⠄⠄⠉⠛⠻⠻⠺⣼⣿⠟⠋⠛⠿⣿⣿
⠋⠉⠁⠄⠄⠄⠄⠄⠄⢻⣿⣿⣶⣄⡀⠄⠄⠄⠄⢀⣤⣾⣿⣿⡀⠄⠄⠄⠄⢹
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢻⣿⣿⣿⣷⡤⠄⠰⡆⠄⠄⠈⠉⠛⠿⢦⣀⡀⡀⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⢿⣿⠟⡋⠄⠄⠄⢣⠄⠄⠄⠄⠄⠄⠄⠈⠹⣿⣀
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⣷⣿⣿⣷⠄⠄⢺⣇⠄⠄⠄⠄⠄⠄⠄⠄⠸⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠹⣿⣿⡇⠄⠄⠸⣿⡄⠄⠈⠁⠄⠄⠄⠄⠄⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢻⣿⡇⠄⠄⠄⢹⣧⠄⠄⠄⠄⠄⠄⠄⠄⠘
'''

def get_quote(api_base_uri, api_random_quote_endpoint):
  try:
    r = requests.get(api_base_uri + '/' + api_random_quote_endpoint)
    r.raise_for_status()
  except HTTPError:
    return False
  else:
    data = r.json()
    quote = data['message']
  
    caption = '\n\n    - Donald J. Trump\n\n'
  
    output = '\n \"' + quote + '\"' + caption 

    return output

def main():
  quote = get_quote(api_base_uri, api_random_quote_endpoint)

  if quote:
    if args.mug:
      print(trump)
    print(quote)
  else:
    print("Looks like Trump ran out of things to say... (Couldn't retrieve a quote)")
  
parser = argparse.ArgumentParser(description='Dump a Trump quote (and optionally some ASCII art of his ugly mug.)\n\nBen Crisp (2019)', formatter_class=RawTextHelpFormatter)
parser.add_argument('--mug', help='Print Trump\'s ugly mug', action='store_true')
args = parser.parse_args()

if __name__ == '__main__':
  main()
